### ISSUE TITLE
question php@7.4-redis --enable-redis-igbinary=yes --enable-redis-lzf=yes

### ISSUE THREAD

**Issue by it-can** [kabel/homebrew-pecl#22]
Is it possible to do something like this?

```
brew reinstall php@7.4-redis --enable-redis-igbinary=yes --enable-redis-lzf=yes
```

**Comment by kabel** [comment]
I've updated the default options to include all the compression and serialization formats at https://github.com/kabel/homebrew-pecl/commit/cfa42233a1c7a04aa8ed4cdd7a7921585bfed1b2
